### ISSUE TITLE
No such module

### ISSUE THREAD

**Issue by alexwall** [dvidelabs/poly.shell#1]
I installed poly this way

`npm install -g poly`

and tried this to run

``` javascript
require('poly').shell().run("touch IWasHere");
```

but got this error:

``` bash
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: No such module
    at Object.<anonymous> (/usr/local/lib/node_modules/poly/lib/password.coffee:5:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/poly/lib/password.coffee:206:4)
    at Module._compile (module.js:432:26)
    at Object..coffee (/usr/local/lib/node_modules/poly/node_modules/coffee-script/lib/coffee-script/coffee-script.js:21:21)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/poly/lib/shell.coffee:6:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/poly/lib/shell.coffee:330:4)
```

CoffeeScript version 1.1.3
node v0.6.5

What's the problem?

**Comment by mikkelfj** [comment]
OK, a bit late. But the npm polyshell name was handed over to another project that needed it more. That is probably why, although now more than 10 years later, it hardly matters. Now we can just use K8s to deploy.
